apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}