apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    resource: {{ .Values.backend.name }}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.backend.name }}
    resource: {{ .Values.backend.name }}
  sessionAffinity: None
  type: ClusterIP