apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for cbomkit backend.
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    resource: {{ .Values.backend.name }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.backend.name }}
  wildcardPolicy: None
