quarkus:
  application:
    name: "CBOMkit"
  http:
    host: 0.0.0.0
    port: ${CBOMKIT_PORT:8081}
    cors:
      ~: true
      origins: ${CBOMKIT_FRONTEND_URL_CORS:http://localhost:8001}
  datasource:
    db-kind: ${CBOMKIT_DB_TYPE:postgresql}
    username: ${CBOMKIT_DB_USERNAME:cbomkit}
    password: ${CBOMKIT_DB_PASSWORD:cbomkit}
    jdbc:
      url: ${CBOMKIT_DB_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
  hibernate-orm:
    database:
      generation: "update"
  websocket:
    dispatch-to-worker: true
  smallrye-openapi:
    info-title: CBOMkit API
    info-description: Service for generating and retrieving CBOMs

cbomkit:
  clone-dir: ${CBOMKIT_CLONEDIR} # specifies the directory in which the cloned Git repositories are stored (temporary)
  scanning:
    java-jar-dir: ${CBOMKIT_JAVA_JAR_DIR:src/main/resources/java/scan/}